name: Make site
on:
  push:
    branches: ["main"]
    tags: ["*"]
jobs:
  makesite:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 21
          cache: sbt
      - name: Setup Ruby
        uses: ruby/setup-ruby@8575951200e472d5f2d95c625da0c7bec8217c42 # v1.161.0
        with:
          ruby-version: '3.1' # Not needed with a .ruby-version file
      - run: gem install jekyll -v 4
      - run: sbt docs/clean;docs/unidoc
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - run: cp ./docs/src/main/site/_docs/CNAME ./docs/target/scala-3.3.1/unidoc/CNAME

      - name: Push site
        uses: s0/git-publish-subdir-action@v2.6.0
        env:
          REPO: self
          BRANCH: gh-pages
          FOLDER: docs/target/scala-3.3.1/unidoc
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
