name: Release
on:
  push:
    branches: ["main"]
    tags: ["*"]
jobs:
  makesite:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 8
          cache: sbt
      - run: sbt docs/publishMicrosite
